<a href="https://colab.research.google.com/github/rayankinikhita/workshop/blob/main/data_model_wrangling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
dataset = pd.read_csv('data_cleaning.csv')

In [ ]:
dataset


Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [ ]:
dataset.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [ ]:
dataset.tail()

Country   Age   Salary Purchased
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [ ]:
X=dataset.iloc[:,:-1].values #to extract with location
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [ ]:
Y=dataset.iloc[:,-1].values
Y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [ ]:
#for numerical column calculate mean and replace nan value with mean 
#for categorical column replace nan with more frequent word
from sklearn.impute import SimpleImputer
import numpy as np

imputer = SimpleImputer(missing_values=np.nan,strategy='mean')
imputer.fit(X[:,1:])
X[:,1:]=imputer.transform(X[:,1:])
print(X)                        

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [ ]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(transformers=[('encoders',OneHotEncoder(),[0])],remainder='passthrough')
X=ct.fit_transform(X)
X

array([[0.0, 1.0, 0.0, 0.0, 44.0, 72000.0],
       [1.0, 0.0, 0.0, 1.0, 27.0, 48000.0],
       [1.0, 0.0, 1.0, 0.0, 30.0, 54000.0],
       [1.0, 0.0, 0.0, 1.0, 38.0, 61000.0],
       [1.0, 0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [0.0, 1.0, 0.0, 0.0, 35.0, 58000.0],
       [1.0, 0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [0.0, 1.0, 0.0, 0.0, 48.0, 79000.0],
       [1.0, 0.0, 1.0, 0.0, 50.0, 83000.0],
       [0.0, 1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [ ]:
#to encode output categorical to numeric
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
Y=le.fit_transform(Y)
Y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [ ]:
#feature scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X[:,[-2,-1]]=sc.fit_transform(X[:,[-2,-1]])
X

array([[0.0, 1.0, 0.0, 0.0, 0.7588743615900191, 0.7588743615900191],
       [1.0, 0.0, 0.0, 1.0, -1.7115038793306812, -1.7115038793306812],
       [1.0, 0.0, 1.0, 0.0, -1.2755547779917342, -1.2755547779917342],
       [1.0, 0.0, 0.0, 1.0, -0.1130238410878752, -0.1130238410878752],
       [1.0, 0.0, 1.0, 0.0, 0.17760889313808956, 0.17760889313808956],
       [0.0, 1.0, 0.0, 0.0, -0.5489729424268224, -0.5489729424268224],
       [1.0, 0.0, 0.0, 1.0, 1.1102230246251565e-16,
        1.1102230246251565e-16],
       [0.0, 1.0, 0.0, 0.0, 1.3401398300419487, 1.3401398300419487],
       [1.0, 0.0, 1.0, 0.0, 1.6307725642679132, 1.6307725642679132],
       [0.0, 1.0, 0.0, 0.0, -0.25834020820085757, -0.25834020820085757]],
      dtype=object)

In [ ]:
from sklearn.model_selection import train_test_split #it splits training and testing data
X_train,X_test,Y_train,Y_test= train_test_split(X,Y,test_size=0.2)

#print(X_train)
print(X_test)
#print(Y_train)
print(Y_test)

[[0.0 1.0 0.0 0.0 -0.25834020820085757 -0.25834020820085757]
 [0.0 1.0 0.0 0.0 0.7588743615900191 0.7588743615900191]]
[1 0]
